local_peer:
  uuid: 3
  name: local peer
  endpoints:
    - type: Udp
      address: "127.0.0.1:7000"
    - type: Tcp
      address: "127.0.0.1:7001"
    - type: Bp
      address: "ipn:1.2"
  color: 3
# This is a local peer with multiple endpoints

peer_list:
  - uuid: 0
    name: john doe
    endpoints:
      - type: Udp
        address: "127.0.0.1:8080"
      - type: Bp
        address: "ipn:1.1"
    color: 0

  - uuid: 1
    name: alice
    endpoints:
      - type: Udp
        address: "127.0.0.1:12345"
    color: 1

  - uuid: 2
    name: bob
    endpoints:
      - type: Tcp
        address: "127.0.0.1:9990"
    color: 2

  - uuid: 3
    name: ipn10
    endpoints:
      - type: Bp
        address: "ipn:10.2"
    color: 2

  - uuid: 4
    name: ipn30
    endpoints:
      - type: Bp
        address: "ipn:30.2"
    color: 2
  - uuid: 5
    name: ud3tn
    endpoints:
      - type: Bp
        address: "ipn:20.2"
    color: 2

  - uuid: 6
    name: vm2-node
    endpoints:
      - type: Bp
        address: "dtn://vm2.local/dtchat"
      - type: Udp
        address: "192.168.1.101:8080"
    color: 4

  - uuid: 7
    name: vm3-gateway
    endpoints:
      - type: Bp
        address: "ipn:100.1"
      - type: Tcp
        address: "192.168.1.102:9001"
    color: 5

  - uuid: 8
    name: vm4-satellite
    endpoints:
      - type: Bp
        address: "dtn://satellite.local/relay"
    color: 6


room_list:
  - uuid: 0
    name: room 1
    participants:
      - 0
      - 1

  - uuid: 1
    name: room 2
    participants:
      - 0
      - 2
