local_peer:
  uuid: 3
  name: local peer
  endpoints:
    - type: Udp
      address: "127.0.0.1:7000"
    - type: Tcp
      address: "127.0.0.1:7001"
    - type: Bp
      address: "PLACEHOLDER_BP_ADDR"
  color: 3
# This is a local peer with multiple endpoints

peer_list:
  - uuid: 0
    name: john doe
    endpoints:
      - type: Udp
        address: "127.0.0.1:8080"
    color: 0

  - uuid: 1
    name: alice
    endpoints:
      - type: Udp
        address: "127.0.0.1:12345"
    color: 1

  - uuid: 2
    name: bob
    endpoints:
      - type: Tcp
        address: "127.0.0.1:9990"
    color: 2

  - uuid: 3
    name: marius
    endpoints:
      - type: Bp
        address: "ipn:20.2"
    color: 2

  - uuid: 4
    name: test
    endpoints:
      - type: Bp
        address: "ipn:10.2"
    color: 2

  - uuid: 5
    name: ipn30
    endpoints:
      - type: Bp
        address: "ipn:30.2"
    color: 2

room_list:
  - uuid: 0
    name: room 1
    participants:
      - 0
      - 1

  - uuid: 1
    name: room 2
    participants:
      - 0
      - 2
