local_peer:
  uuid: 3
  name: local peer
  endpoints:
    - address: "127.0.0.1:7001"
      protocol: tcp
    - address: "127.0.0.1:7000"
      protocol: udp
  color: 3
# This is a local peer with multiple endpoints

peer_list:
  - uuid: 0
    name: john doe
    endpoints:
      - address: "127.0.0.1:8080"
        protocol: udp
    color: 0

  - uuid: 1
    name: alice
    endpoints:
      - address: "127.0.0.1:12345"
        protocol: udp
    color: 1

  - uuid: 2
    name: bob
    endpoints:
      - address: "127.0.0.1:9990"
        protocol: tcp
    color: 2

room_list:
  - uuid: 0
    name: room 1
    participants:
      - 0
      - 1

  - uuid: 1
    name: room 2
    participants:
      - 0
      - 2
