local_peer:
  uuid: "Makuhari"
  name: "Makuhari"
  endpoints:
    - type: Bp
      address: "ipn:201.1"
    - type: Udp
      address: "192.168.120.2:8080"
  color: 4

peer_list:
  - uuid: "moon-base"
    name: "Moon Base"
    endpoints:
      - type: Bp
        address: "ipn:401.1"
      - type: Udp
        address: "192.168.130.2:8080"
    color: 3

  - uuid: "relay-102"
    name: "Relay Node 102"
    endpoints:
      - type: Bp
        address: "ipn:102.1"
    color: 2

  - uuid: "relay-101"
    name: "Relay Node 101"
    endpoints:
      - type: Bp
        address: "ipn:101.1"
    color: 3

room_list:
  - uuid: "earth-moon-room"
    name: "Earth-Moon Communications"
    participants:
      - "moon-station"
      - "earth-station"
