local_peer:
  uuid: 3
  name: local peer
  endpoints:
    - type: Udp
      address: "127.0.0.1:7000"
    - type: Tcp
      address: "127.0.0.1:7001"
    - type: Bp
      address: "ipn:3.1"
  color: 3
# This is a local peer with multiple endpoints

peer_list:
  - uuid: 0
    name: john doe
    endpoints:
      - type: Udp
        address: "127.0.0.1:8080"
      - type: Bp
        address: "ipn:0.1"
    color: 0

  - uuid: 1
    name: alice
    endpoints:
      - type: Udp
        address: "127.0.0.1:12345"
      - type: Bp
        address: "ipn:1.1"
    color: 1

  - uuid: 2
    name: bob
    endpoints:
      - type: Tcp
        address: "127.0.0.1:9990"
      - type: Bp
        address: "ipn:2.1"
    color: 2

room_list:
  - uuid: 0
    name: room 1
    participants:
      - 0
      - 1

  - uuid: 1
    name: room 2
    participants:
      - 0
      - 2
